[package]
name = "adextopa-core"
version = "0.1.0"
edition = "2021"

[features]
v1 = []
default = ["v1"]

[dependencies]
substring = "1.4.5"
regex = "1.5.4"
adextopa_macros = { path = "./adextopa_macros" }
lazy_static = "1.4.0"
